config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#welcome'
  get 'about', to: 'pages#about'
  get 'package', to: 'pages#package'
  get 'portfolio', to: 'pages#portfolio'

  #resources :contacts, only:[:new, :create]

  get 'basics', to: 'basics#new'
  post 'basics', to: 'basics#create'

  get 'standards', to: 'standards#inquire'
  post 'standards', to: 'standards#success'

  get 'packages', to: 'packages#new'
  post 'packages', to: 'packages#create'

  get 'contacts', to: 'contacts#index'
  post 'contacts', to: 'contacts#sent'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basic.rb
class Basic < MailForm::Base
  attribute :name,  :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate =>true

  def headers
    {
      :to => %(<#{email}>),
      :subject => "Package: BASIC",
      :from => %(#{name}),
      :message => %("#{message}")
    }
  end

end

app/models/business.rb
class Business < MailForm::Base
  attribute :name,  :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate =>true

  def headers
    {
      :to => %(<#{email}>),
      :subject => "Package: ECOMMERCE",
      :from => %(#{name}),
      :message => %("#{message}")
    }
  end

end

app/models/contact.rb
class Contact < MailForm::Base
  attributes :name,  :validate => true
  attributes :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message, :validate =>true

  def headers
    {
      :to => %(<#{email}>),
      :subject => "Package: ECOMMERCE",
      :from => %(#{name}),
      :message => %("#{message}")
    }
  end

end

app/models/ecommerce.rb
class Ecommerce < MailForm::Base

  attributes :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :name, :validate =>true
  attributes :message, :validate =>true

  def headers
    {
      :to => %(<#{email}>),
      :subject => "Inquiry",
      :from => %(#{name}),
      :message => %("#{message}")
    }
  end

end

app/models/package.rb
class Package < MailForm::Base
  attribute :name,  :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate =>true

  def headers
    {
      :to => %(<#{email}>),
      :subject => "Package: BASIC",
      :from => %(#{name}),
      :message => %("#{message}")
    }
  end

end

app/models/standard.rb
class Standard < MailForm::Base
  attribute :name,  :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate =>true


  def headers
    {
      :to => %(<#{email}>),
      :subject => "Package: STANDARD",
      :from => %(#{name}),
      :message => %("#{message}")
    }
  end

end

app/controllers/basics_controller.rb
class BasicsController < ApplicationController


    def new
      @basic =Basic.new
    end

    def create
      @basic = Basic.new(params[:basic])
      @basic.request = request

      if @basic.deliver
        flash.now[:error] = nil
      else
        flash.now[:error] = 'Cannot send message'
        render :new
      end
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact =Contact.new
  end

  def sent
    @contact = Contact.new(params[:contact])
    @contact.request = request

    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message'
      render :index
    end
  end


end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController

      def new
        @package =Package.new
      end

      def create
        @package = Package.new(params[:package])
        @package.request = request

        if @package.deliver
          flash.now[:error] = nil
        else
          flash.now[:error] = 'Cannot send message'
          render :new
        end
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def welcome
    end

    def about
    end

    def package
    end

    def portfolio
    end

end

app/controllers/standards_controller.rb
class StandardsController < ApplicationController

      def inquire
        @standard =Standard.new
      end

      def success
        @standard = Standard.new(params[:standard])
        @standard.request = request

        if @standard.deliver
          flash.now[:error] = nil
        else
          flash.now[:error] = 'Cannot send message'
          render :inquire
        end
      end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_aboutme.html.erb
<ul class="cd-hero-slider">
    <li class="selected">
            <div class="heading">
            <h1>About Me</h1>

            </div>
            <div class="cd-half-width second-slide">
            <div class="container">
                <div class="row">
                <div class="col-md-12">
                    <div class="content second-content">
                    <div class="row">
                        <div class="col-md-7 left-image">
                        <img src="img/left-about-image.jpg">
                        </div>
                        <div class="col-md-5">
                        <div class="right-about-text">
                            <h4>Who am I?</h4>
                            <p style="text-align: justify;">I'm a Web Developer and technology enthusiast who loves to use my creative
                                skills to solve complex solutions.  I have a passion for keeing up-to-date
                                regarding the latest trends involving technology. </p>
                            <p style="text-align: justify;">As a web developer I focused on customer satisfaction, I manage all aspects of web development from concept to requirements definition, design, development, maintenance and user support. </p>


                        </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-7">
                        <div class="left-about-text">
                            <h3>What I do?</h3>
                            <p>I provide a complete web design service for businesses and individuals. I will help you from initial prototype stage through to implementation, maintenance and support.</p>
                            <p>My strengths are, competitive pricing, good service and fast turnaround time.</p>

                              <h5>Services</h5>
                              <ul>
                                  <ol> - Custom Website Design, Outsourced Web Design, Graphic Design, Website Maintenance,</ol>
                                  <ol>  &nbsp; Email-Marketing(Newsletter) </ol>
                              </ul>

                              <h5>Web Technology Platforms</h5>
                              <ul>
                                  <ol> - Ruby on Rails, Laravel framework (PHP), WordPress and WooCommerce </ol>
                              </ul>

                              <br>
                          </div>
                        </div>
                        <div class="col-md-5 right-image">
                        <img src="img/webdesign2.jpg">
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
</li>
</ul>

app/views/layouts/_footer.html.erb
      <!-- FOOTER -->
           <footer data-stellar-background-ratio="0.5">
                <div class="container">
                     <div class="row">

                          <div class="col-md-3 col-sm-12">
                               <div class="footer-thumb footer-info">
                                 <h2>Technology Platform</h2>
                                 <ul class="footer-link">
                                   <li><%= link_to "Ruby on Rails", about_path %></li>
                                   <li><%= link_to "Laravel Framework (PHP)",about_path %></li>
                                   <li><%= link_to "WordPress and WooCommerce", about_path%></li>
                                 </ul>

                               </div>
                          </div>

                          <div class="col-md-2 col-sm-4">
                               <div class="footer-thumb">
                                 <h2>Services</h2>
                                       <ul class="footer-link">

                                           <li><%= link_to "Web Design & Development", package_path%></li>
                                           <li><%= link_to "Website Packages", package_path%></li>
                                           <li><%= link_to "Outsourcing", package_path%></li>
                                           <li><%= link_to "Graphic Design", package_path%></li>
                                           <li><%= link_to "Website Maintenance", package_path%></li>
                                       </ul>

                               </div>
                          </div>

                          <div class="col-md-2 col-sm-4">
                               <div class="footer-thumb">
                                 <h2>Quick Links</h2>
                                   <ul class="footer-link">
                                     <li><%= link_to "About Me",about_path%></li>
                                     <li><%= link_to "Packages",package_path%></li>
                                     <li><%= link_to "Porfolio",portfolio_path%></li>
                                     <li><%= link_to "Inquire",contacts_path%></li>

                                   </ul>

                               </div>
                          </div>

                          <div class="col-md-2 col-sm-4">
                               <div class="footer-thumb">
                                    <h2>Contact Me</h2>
                                    <p class="fa fa-comments"> Skype: itcebu</p><br>
                                    <p class="fa fa-envelope"> Email: denver.aleta91@gmail.com</p>
                               </div>
                          </div>

                          <div class="col-md-12 col-sm-12">
                               <div class="footer-bottom">
                                    <div class="col-md-6 col-sm-5">
                                         <div class="copyright-text">
                                              <p>Copyright &copy; 2018 DenverWorks</p>
                                         </div>
                                    </div>
                                    <div class="col-md-6 col-sm-7">
                                         <div class="phone-contact">
                                              <p>Viber: <span>(+63) 917-301-3454</span></p>
                                         </div>
                                         <ul class="social-icon">
                                              <li><a href="https://www.facebook.com/denver.aleta.71" target="_blank" class="fa fa-facebook-square" attr="facebook icon"></a></li>
                                              <li><a href="https://twitter.com/bembemAleta" target="_blank" class="fa fa-twitter"></a></li>
                                              <li><a href="https://www.instagram.com/bembemaleta/" target="_blank" class="fa fa-instagram"></a></li>
                                         </ul>
                                    </div>
                               </div>
                          </div>

                     </div>
                </div>
           </footer>

app/views/layouts/_navslider.html.erb
      <div class="cd-slider-nav">
          <nav>
              <span class="cd-marker item-1"></span>
              <ul>
                <li class="selected"><div class="image-icon"><%= link_to image_tag("home-icon.png", alt:"Home"),root_path%></div><h6>Welcome</h6></li>
                <li><div class="image-icon"><%= link_to image_tag("about-icon.png", alt:"About Me"),about_path%></div><h6>About Me</h6></li>
                <li><div class="image-icon"><%= link_to image_tag("featured-icon.png", alt:"Package"),package_path%></div><h6>Packages</h6></li>
                <li><div class="image-icon"><%= link_to image_tag("projects-icon.png", alt:"Porfolio"),portfolio_path%></div><h6>Porfolio</h6></li>
                <li><div class="image-icon"><%= link_to image_tag("contact-icon.png", alt:"Inquire"),contacts_path%></div><h6>Inquire</h6></li>
              </ul>
          </nav>
        </div> <!-- .cd-slider-nav -->

app/views/layouts/_package.html.erb
<ul class="cd-hero-slider">
    <li class="selected">
            <div class="heading">
                <h1>Web Design Packages</h1>
            </div>
              <div class="cd-half-width third-slide">
                <div class="container">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="content third-content">
                        <div class="row">
                            <div class="section-headlines text-center">
                              <h2>Web Design Pricing</h2>
                              <p>My aim is simple; I want to ensure your business penetrates the market and finds its way to be a top competitor.</p>
                            </div>

                             <div class="row-fluid" style="margin-left: 7px;">
                                <div class="pricing-table row-fluid text-center">
                                  <div class="span4">
                                    <div class="plan">
                      								<div class="plan-name">
                      									<h2>BASIC</h2>
                      									<p class="muted">Perfect for small budget</p>
                      								</div>
                      								<div class="plan-price">
                      									<b>$43.00 </b> / month
                      								</div>
                      								<div class="plan-details">
                      									<div>
                      										<b>RESPONSIVE & MOBILE READY</b>
                      									</div>
                      									<div>
                      										<b>HOME PAGE FEATURED SLIDER</b>
                      									</div>
                      									<div>
                      										<b>IMAGE GALLERY</b>
                      									</div>
                                        <div>
                      										<b>CONTACT FORM</b>
                      									</div>
                                        <div>
                      										<b>SEARCH ENGINE FRIENDLY</b>
                      									</div>
                                        <div>
                      										<b>4 WEB PAGES</b>
                      									</div>
                                        <div>
                      										<b>1 Included Free Domain Registration (ie: www.your-business-name.com)</b>
                      									</div>
                                        <div>
          										            <b>1 Web Email Address Setup (ie: john@your-business-name.com)</b>
                      									</div>
                                        <div>
                      										<b>Hosting Storage (5GB) </b>
                      									</div>
                                        <div>
                      										<b>Site Content Revision and Maintenance</b>
                      									</div>

                      								</div>
                      								<div class="plan-action">
                                        <%= link_to "Request for Quotation",basics_path, class:"btn btn-block btn-large"%>
                      								</div>
                      							</div>
                                </div>


                                  <div class="span4">
                                    <div class="plan prefered">
                                      <div class="plan-name">
                                        <h2>STANDARD</h2>
                                        <p class="muted">Perfect for medium budget</p>
                                      </div>
                                      <div class="plan-price">
                                        <b>$53.00</b> / month
                                      </div>
                                      <div class="plan-details">
                                        <div>
                                          <b>RESPONSIVE & MOBILE READY</b>
                                        </div>
                                        <div>
                                          <b>IMAGE GALLERY</b>
                                        </div>
                                        <div>
                                          <b>CONTACT FORM</b>
                                        </div>
                                        <div>
                                          <b>SEARCH ENGINE FRIENDLY</b>
                                        </div>
                                        <div>
                                          <b>6 WEB PAGES</b>
                                        </div>
                                        <div>
                                          <b>CONTACT FORM</b>
                                        </div>
                                        <div>
                                          <b>Social Media Marketing  - Integration to your website</b> (Facebook, Twitter, Instagram)
                                        </div>
                                        <div>
                                          <b>1 Included Free Domain Registration (ie: www.your-business-name.com)</b>
                                        </div>
                                        <div>
                                          <b>5 Web Email Address Setup (ie: john@your-business-name.com)</b>
                                        </div>
                                        <div>
                                          <b>Hosting Storage (25GB) </b>
                                        </div>
                                        <div>
                                          <b>Site Content Revision and Maintenance</b>
                                        </div>

                                      </div>
                                      <div class="plan-action">
                                      <%= link_to "Request for Quotation",standards_path, class:"btn btn-success btn btn-block btn-large"%>
                                      </div>
                                    </div>
                                  </div>

                                  <div class="span4">
                                    <div class="plan">
                      								<div class="plan-name">
                      									<h2>ECOMMERCE</h2>
                      									<p class="muted">Perfect for Online business</p>
                      								</div>
                      								<div class="plan-price">
                      									<b>$80.00</b> / month
                      								</div>
                      								<div class="plan-details">
                      									<div>
                      										<b>RESPONSIVE & MOBILE READY</b>
                      									</div>
                      									<div>
                      										<b>HOME PAGE FEATURED SLIDER</b>
                      									</div>
                      									<div>
                      										<b>BILLING & SHIPPING FORMS</b>
                      									</div>
                                        <div>
                                          <b>ORDER & DELIVERY MANAGEMENT</b>
                                        </div>
                                        <div>
                                          <b>LIVE CHAT </b>
                                        </div>
                                        <div>
                                          <b>ADMIN DASH BOARD </b>
                                        </div>
                                        <div>
                                          <b>Social Media Marketing  - Integration to your website</b> (Facebook, Twitter, Instagram)
                                        </div>
                                        <div>
                                          <b>1 Included Free Domain Registration (ie: www.your-business-name.com)</b>
                                        </div>
                                        <div>
                                          <b>5 Web Email Address Setup (ie: john@your-business-name.com) </b>
                                        </div>
                                        <div>
                                          <b>Hosting Storage (25GB) </b>
                                        </div>
                                        <div>
                                          <b>Site Content Revision and Maintenance </b>
                                        </div>
                                        <div>
                                          <b>Payment Gateways (ie. Credit Card, Paypal and others) </b>
                                        </div>
                      								</div>
                      								<div class="plan-action">
                      					        <%= link_to "Request for Quotation",packages_path, class:" btn btn-block btn-large"%>

                                  		</div>
                      							</div>




                                  </div>

                              </div>
                           </div>

                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
</li>
</ul>

app/views/layouts/_projects.html.erb
<ul class="cd-hero-slider">
    <li class="selected">
          <div class="heading">
                <h1>My Portfolio</h1>
            <span>Here you can check my recent projects</span>
          </div>
            <div class="cd-half-width fourth-slide">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="content fourth-content">
                      <div class="row">

                        <div class="col-md-4 col-sm-5 project-item ">
                            <a href="http://www.avava.com.au" rel="noopener noreferrer" target="_blank"><img class = "img-thumbnail" src="img/Avava.jpg"></a>
                          </div>
                          <div class="col-md-4 col-sm-5 project-item">
                            <a href="http://www.satarboat.com.au" rel="noopener noreferrer" target="_blank"><img class = "img-thumbnail" src="img/satarboat.jpg"></a>
                          </div>
                          <div class="col-md-4 col-sm-5 project-item">
                            <a href="http://www.invotrends.com" rel="noopener noreferrer" target="_blank"><img class = "img-thumbnail" src="img/Invotrends.jpg"></a>
                          </div>
                          <div class="col-md-4 col-sm-5 project-item">
                            <a href="http://www.parkpoint.com.au" rel="noopener noreferrer" target="_blank"><img class = "img-thumbnail" src="img/Parkpoint.jpg"></a>
                          </div>
                          <div class="col-md-4 col-sm-5 project-item">
                            <a href="https://www.vestahomes.com.au" rel="noopener noreferrer" target="_blank"><img class = "img-thumbnail" src="img/vesta.jpg"></a>
                          </div>
                          <div class="col-md-4 col-sm-5 project-item">
                            <a href="http://www.vestahomes.com.ph" rel="noopener noreferrer" target="_blank"><img class = "img-thumbnail" src="img/vesta2.jpg"></a>
                          </div>



                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>

app/views/layouts/_welcome.html.erb
<ul class="cd-hero-slider">
    <li class="selected">

      <div class="heading" style="margin-bottom: 150px;">
          <h1>Freelance Web Designer</h1>
          <span>Welcome To My Page</span>
      </div>
        <div class="cd-full-width first-slide">

            <div class="container">
            <div class="row">
                <div class="col-md-12">
                  <div class="content first-content">
                    <div class="row">
                        <div class="col-md-4 col-sm-5" >
                          <div class="about-info">
                          <p>I'm a Web Developer and technology enthusiast who loves to use my creative
                              skills to solve complex solutions.  I have a passion for keeing up-to-date
                              regarding the latest trends involving technology.<span><%= link_to "more", about_path %></span> </p>
                          </div>
                         </div>

                         <div class="col-md-4 col-sm-3" >
                          <div class="about-info skill-thumb">
                           <strong>Web Design</strong>
                           <span class="pull-right">95%</span>
                              <div class="progress">
                                <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%;"></div>
                              </div>

                                <strong>Graphic Design</strong>
                                <span class="pull-right">90%</span>
                               <div class="progress">
                                    <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;"></div>
                               </div>

                               <strong>Mobile Responsive</strong>
                               <span class="pull-right">95%</span>
                                <div class="progress">
                                     <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%;"></div>
                                </div>

                                <strong>CMS Admin</strong>
                                <span class="pull-right">90%</span>
                                <div class="progress">
                                     <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;"></div>
                                </div>
                            </div>
                          </div>

                        <div class="col-md-3 col-sm-3" >
                          <div class="about-image">
                            <img src="img/bembem.jpg" class="img-responsive">
                          </div>
                        </div>
                  </div>
                </div>
                </div>
            </div>
            </div>

        </div>
 </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freelance Web Designer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

       <script src='https://www.google.com/recaptcha/api.js'></script>
       <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="css/fontAwesome.css">
        <link rel="stylesheet" href="css/templatemo-style.css">
        <link rel="stylesheet" href="css/style.css">



        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

  </head>

  <body>


      <div class="overlay"></div>
      <section class="top-part">
        <video controls autoplay loop>
          <source src="videos/video.mp4" type="video/mp4">
          <source src="videos/video.ogg" type="video/ogg">
        Your browser does not support the video tag.
        </video>
      </section>

        <section class="cd-hero">
          <%=render 'layouts/navslider'%>
          <%= yield%>


       </section> <!-- .cd-hero -->



        <%=render 'layouts/footer'%>
        <%= debug(params)if Rails.env.development?%>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>

        <script src="js/vendor/bootstrap.min.js"></script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>
        <script  src="js/index.js"></script> <!-- For SLIDER --!>

  </body>
</html>

app/views/pages/about.html.erb
  <%= render  partial:'layouts/aboutme'%>

app/views/pages/package.html.erb
  <%= render  partial:'layouts/package'%>

app/views/pages/portfolio.html.erb
<ul class="cd-hero-slider">
  <%= render  partial:'layouts/projects'%>
 </ul> <!-- .cd-hero-slider -->

app/views/pages/welcome.html.erb
  <%= render  partial:'layouts/welcome'%>